Traceback (most recent call last):
  File "main.py", line 189, in <module>
    tf.app.run(main=_main)
  File "C:\Users\emrul\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 179, in _main
    _eval_epoch(sess, gamma_, lambda_g_, epoch, 'val')
  File "main.py", line 130, in _eval_epoch
    bleu = tx.evals.corpus_bleu_moses(refs, hyps)
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\site-packages\texar\tf\evals\bleu_moses.py", line 154, in corpus_bleu_moses
    multi_bleu_cmd, stdin=hyp_input, stderr=subprocess.STDOUT)
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\emrul\anaconda3\envs\ProjectTST\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 nâ€™est pas une application Win32 valide
